### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ghost** [Aikku93/ulc-codec#2]
mkdir -p build
Fourier_DCT2.c
In file included from fourier/Fourier_DCT2.c:3:
fourier/Fourier_Helper.h:81:11: error: unknown type name ‘__m128’
   81 |   typedef __m128 Fourier_Vec_t;
      |           ^~~~~~
fourier/Fourier_Helper.h: In function ‘FOURIER_VINTERLEAVE’:
fourier/Fourier_Helper.h:105:15: warning: implicit declaration of function ‘_mm_unpacklo_ps’ [-Wimplicit-function-declaration]
  105 |         *Lo = _mm_unpacklo_ps(a, b);
      |               ^~~~~~~~~~~~~~~
fourier/Fourier_Helper.h:106:15: warning: implicit declaration of function ‘_mm_unpackhi_ps’ [-Wimplicit-function-declaration]
  106 |         *Hi = _mm_unpackhi_ps(a, b);
      |               ^~~~~~~~~~~~~~~
fourier/Fourier_Helper.h: In function ‘FOURIER_VSPLIT_EVEN_ODD’:
fourier/Fourier_Helper.h:109:17: warning: implicit declaration of function ‘_mm_shuffle_ps’ [-Wimplicit-function-declaration]
  109 |         *Even = _mm_shuffle_ps(l, h, 0x88);
      |                 ^~~~~~~~~~~~~~
fourier/Fourier_Helper.h: In function ‘Fourier_Sin’:
fourier/Fourier_Helper.h:92:37: warning: implicit declaration of function ‘_mm_mul_ps’ [-Wimplicit-function-declaration]
   92 | # define FOURIER_VMUL(x, y)         _mm_mul_ps(x, y)
      |                                     ^~~~~~~~~~
fourier/Fourier_Helper.h:196:29: note: in expansion of macro ‘FOURIER_VMUL’
  196 |         Fourier_Vec_t x2  = FOURIER_VMUL(x, x);
      |                             ^~~~~~~~~~~~
fourier/Fourier_Helper.h:100:37: warning: implicit declaration of function ‘_mm_add_ps’ [-Wimplicit-function-declaration]
  100 | #  define FOURIER_VFMA(x, y, a)     _mm_add_ps(_mm_mul_ps(x, y), a)
      |                                     ^~~~~~~~~~
fourier/Fourier_Helper.h:197:29: note: in expansion of macro ‘FOURIER_VFMA’
  197 |         Fourier_Vec_t Res = FOURIER_VFMA(x2, FOURIER_VSET1(+0x1.3C8B08p-13f), FOURIER_VSET1(-0x1.3237ECp-8f));
      |                             ^~~~~~~~~~~~
fourier/Fourier_Helper.h:88:37: warning: implicit declaration of function ‘_mm_set1_ps’ [-Wimplicit-function-declaration]
   88 | # define FOURIER_VSET1(x)           _mm_set1_ps(x)
      |                                     ^~~~~~~~~~~
fourier/Fourier_Helper.h:100:62: note: in definition of macro ‘FOURIER_VFMA’
  100 | #  define FOURIER_VFMA(x, y, a)     _mm_add_ps(_mm_mul_ps(x, y), a)
      |                                                              ^
fourier/Fourier_Helper.h:197:46: note: in expansion of macro ‘FOURIER_VSET1’
  197 |         Fourier_Vec_t Res = FOURIER_VFMA(x2, FOURIER_VSET1(+0x1.3C8B08p-13f), FOURIER_VSET1(-0x1.3237ECp-8f));
      |                                              ^~~~~~~~~~~~~
fourier/Fourier_DCT2_Template.h: In function ‘Fourier_DCT2_Template’:
fourier/Fourier_Helper.h:84:37: warning: implicit declaration of function ‘_mm_load_ps’ [-Wimplicit-function-declaration]
   84 | # define FOURIER_VLOAD(Src)         _mm_load_ps(Src)
      |                                     ^~~~~~~~~~~
fourier/Fourier_Helper.h:93:52: note: in definition of macro ‘FOURIER_VREVERSE’
   93 | # define FOURIER_VREVERSE(x)        _mm_shuffle_ps(x, x, 0x1B)
      |                                                    ^
fourier/Fourier_DCT2_Template.h:30:72: note: in expansion of macro ‘FOURIER_VLOAD’
   30 |                         SrcHi -= FOURIER_VSTRIDE; b = FOURIER_VREVERSE(FOURIER_VLOAD(SrcHi));
      |                                                                        ^~~~~~~~~~~~~
fourier/Fourier_Helper.h:91:37: warning: implicit declaration of function ‘_mm_sub_ps’ [-Wimplicit-function-declaration]
   91 | # define FOURIER_VSUB(x, y)         _mm_sub_ps(x, y)
      |                                     ^~~~~~~~~~
fourier/Fourier_DCT2_Template.h:33:29: note: in expansion of macro ‘FOURIER_VSUB’
   33 |                         d = FOURIER_VSUB(a, b);
      |                             ^~~~~~~~~~~~
fourier/Fourier_Helper.h:86:37: warning: implicit declaration of function ‘_mm_store_ps’ [-Wimplicit-function-declaration]
   86 | # define FOURIER_VSTORE(Dst, x)     _mm_store_ps(Dst, x)
      |                                     ^~~~~~~~~~~~
fourier/Fourier_DCT2_Template.h:34:25: note: in expansion of macro ‘FOURIER_VSTORE’
   34 |                         FOURIER_VSTORE(DstLo, s); DstLo += FOURIER_VSTRIDE;
      |                         ^~~~~~~~~~~~~~
make: *** [Makefile:117: build/fourier/Fourier_DCT2.c.o] Error 1

**Comment by Aikku93** [comment]
Hi, thanks for the report. I believe this issue happens because the Makefile assumes that the target is x86 and that all related functionality (including SSE and AVX) is available to the compiler.

I'll try to add proper non-x86 support in the Makefile soon-ish (hopefully within a week or so; this is just a hobby project, and I do have a completely unrelated full-time job), but in the meantime, may I ask which platform your compiler is targeting (just to make sure this isn't another issue)?

**Comment by Aikku93** [comment]
I've commited some changes so that it will hopefully work now. Please let me know if it does or doesn't, so I can close the issue or try something else.

**Comment by ghost** [comment]
> Hi, thanks for the report. I believe this issue happens because the Makefile assumes that the target is x86 and that all related functionality (including SSE and AVX) is available to the compiler.
> 
> I'll try to add proper non-x86 support in the Makefile soon-ish (hopefully within a week or so; this is just a hobby project, and I do have a completely unrelated full-time job), but in the meantime, may I ask which platform your compiler is targeting (just to make sure this isn't another issue)?

Just my native platform. I'm using MSYS2-UCRT64, on Windows 10 (build 22H2, 64 Bit).
The same problem occurs on Cygwin as well.

**Comment by ghost** [comment]
> I've commited some changes so that it will hopefully work now. Please let me know if it does or doesn't, so I can close the issue or try something else.

That seems to have fixed the problem!

**Comment by Aikku93** [comment]
> I'm using MSYS2-UCRT64

I think I see the real problem now. The Fourier_Helper.h file is scanning for `_M_IX86`, `_M_X64`, or `__i386__` being defined to enable the SSE/AVX-specific code, and previously would just use "generic" versions of the routines by not bringing any CPUID or SSE/AVX headers, but wouldn't stop the SSE/AVX files from being compiled. This would cause the SSE/AVX code to assume that the the right intrinsics files were loaded and things would go awry.

Are you getting any "Unknown compiler. Disabling x86-specific code." warnings, and/or are the SSE/AVX files being compiled? I'm actually still running Windows 7, so I can't exactly test what happens with UCRT versions of gcc.
